"""empty message

Revision ID: 7df4ad3afee8
Revises: b774c9bf9404
Create Date: 2024-07-20 13:42:35.516828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df4ad3afee8'
down_revision = 'b774c9bf9404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s_is_approved', sa.Boolean(), nullable=True))
        batch_op.alter_column('s_password',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('s_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('s_is_approved')

    # ### end Alembic commands ###
