"""empty message

Revision ID: b774c9bf9404
Revises: cc7fab27f10c
Create Date: 2024-07-01 20:36:06.596628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b774c9bf9404'
down_revision = 'cc7fab27f10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transaction')
    op.drop_table('Customer')
    op.drop_table('InventoryItems')
    op.drop_table('Staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Staff',
    sa.Column('s_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Staff_s_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('s_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('s_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('s_isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('s_contact', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('s_password', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('s_id', name='Staff_pkey'),
    sa.UniqueConstraint('s_email', name='Staff_s_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('InventoryItems',
    sa.Column('item_sku', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('item_sku', name='InventoryItems_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Customer',
    sa.Column('c_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Customer_c_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('c_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('c_contact', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('c_id', name='Customer_pkey'),
    sa.UniqueConstraint('c_email', name='Customer_c_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Transaction',
    sa.Column('t_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Transaction_t_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('t_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('t_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('t_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inventory_item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.c_id'], name='Transaction_customer_id_fkey'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['InventoryItems.item_sku'], name='Transaction_inventory_item_id_fkey'),
    sa.ForeignKeyConstraint(['staff_id'], ['Staff.s_id'], name='Transaction_staff_id_fkey'),
    sa.PrimaryKeyConstraint('t_id', name='Transaction_pkey')
    )
    # ### end Alembic commands ###
